"""
Wordlists from the original geogrids library
"""

fucks = [
    'anus', 'arse', 'arsehole', 'ass', 'assbag', 'assbanger', 'assbite',
    'asscracker', 'asses', 'assfuck', 'asshole', 'asslicker', 'assmuncher',
    'asswart', 'asswipe', 'bastard', 'beaner', 'bitch', 'bitching', 'blowjob',
    'boner', 'boytoy', 'brotherfucker', 'bullshit', 'buttplug', 'buttfucker',
    'cameltoe', 'cancer', 'carpetmuncher', 'chesticle', 'chink', 'chode',
    'clit', 'clitfuck', 'clitoris', 'clusterfuck', 'cock', 'cockface',
    'cockfucker', 'cockhead', 'cockjockey', 'cockmaster', 'cocksucker',
    'coochie', 'coon', 'cooter', 'cracker', 'cum', 'cumbubble', 'cumdumpster',
    'cumguzzler', 'cumjockey', 'cumslut', 'cumtart', 'cunnie', 'cunnilingus',
    'cunt', 'cuntass', 'cuntface', 'cunthole', 'cuntlicker', 'cuntrag',
    'cuntslut', 'damn', 'deggo', 'dick', 'dick-sneeze', 'dickbag',
    'dickbeaters', 'dickface', 'dickfucker', 'dickhead', 'dickhole',
    'dickjuice', 'dickmilk', 'dickmonger', 'dickslap', 'dicksucker',
    'dicksucking', 'dicktickler', 'dickwad', 'dickweasel', 'dickweed',
    'dickwod', 'dildo', 'dipshit', 'doochbag', 'dookie', 'douche', 'douche-fag',
    'douchebag', 'douchewaffle', 'dumbass', 'dumbfuck', 'dumbshit', 'dyke',
    'eightball', 'fag', 'fagbag', 'fagfucker', 'faggot', 'faggotcock',
    'fagtard', 'fatass', 'fellatio', 'feltch', 'flamer', 'fuck', 'fuckass',
    'fuckbag', 'fuckboy', 'fuckbutt', 'fucker', 'fuckface', 'fuckhead',
    'fuckhole', 'fucking', 'fucknut', 'fucknutt', 'fuckoff', 'fucks',
    'fuckstick', 'fucktard', 'fucktart', 'fucktastic', 'fucktoy', 'fuckup',
    'fuckwad', 'fuckwitt', 'gangbang', 'gay', 'gayass', 'gaybob', 'gaydo',
    'gayfuck', 'gayfuckist', 'gaylord', 'gaytard', 'gaywad', 'gimp', 'meecrob',
    'goddamn', 'gooch', 'gook', 'gringo', 'guido', 'handjob', 'hardon', 'heeb',
    'hell', 'ho', 'homo', 'honkey', 'humping', 'jackass', 'jap', 'jerk',
    'jerkoff', 'jigaboo', 'jizz', 'kike', 'kraut', 'kyke', 'lameass', 'lardass',
    'lesbian', 'lesbo', 'lezzie', 'mcfagget', 'mick', 'motherfucker', 'muff',
    'muffdiver', 'negro', 'nigaboo', 'nigga', 'nigger', 'niggers', 'niglet',
    'nutsack', 'paki', 'panooch', 'pecker', 'penis', 'penisfucker', 'piss',
    'pissoff', 'pissflaps', 'pimp', 'polesmoker', 'pollock', 'poon', 'poonani',
    'prick', 'punanny', 'punta', 'pussy', 'pussylicker', 'puto', 'queef',
    'queer', 'renob', 'rimjob', 'ruski', 'sandnigger', 'schlong', 'scrote',
    'semen', 'shit', 'shitass', 'shitbag', 'shitcanned', 'shitfaced',
    'shithole', 'shithouse', 'shitstain', 'shitter', 'shitting', 'shitty',
    'shiz', 'skank', 'skeet', 'slut', 'smeg', 'snatch', 'spick', 'splooge',
    'spook', 'suckass', 'supercock', 'supercunt', 'superfuck', 'supergay',
    'supershit', 'tard', 'testicle', 'thundercunt', 'tit', 'titfuck', 'twat',
    'twatlips', 'twats', 'twatwaffle', 'unclefucker', 'vagina', 'wank',
    'wanker', 'wankjob', 'wetback', 'whore', 'whorebag', 'whoreface', 'wop',
    'condom', 'porn', 'eunuch', 'rape', 'pedophile', 'sadist', 'masochist',
    'coitus', 'cunnilingus', 'orgy', 'orgasm', 'masturbation', 'penetrate',
    'bawbag', 'fud', 'glakit', 'scabby', 'whalluper', 'cludgie', 'doaber',
    'hamshank', 'lavvie', 'skelpit', 'bellend', 'bloody', 'blimey', 'clunge',
    'crap', 'fanny', 'sideways', 'nonce', 'penguin', 'flaps', 'poof', 'slag',
    'toff', 'randy', 'raunchy', 'spunk', 'wankstain', 'bampot', 'barmy', 'berk',
    'bint', 'blighter', 'blooming', 'bollocks', 'charva', 'chav', 'chauvinist',
    'cheeky', 'cobblers', 'cockup', 'codger', 'dago', 'divvy', 'dodgy', 'dozy',
    'duffer', 'eejit', 'git', 'gormless', 'grotty', 'manky', 'minger', 'munter',
    'naff', 'nancy', 'numpty', 'nutter', 'pikey', 'pillock', 'plonker', 'poxy',
    'prat', 'scrubber', 'skanky', 'trollop', 'tyke', 'wally', 'wazzack',
    'abydocomist', 'bedswerver', 'bespawler', 'bobolyne', 'cumberworld',
    'dalcop', 'dewbeater', 'dorbel', 'dratepoke', 'driggledraggle', 'fopdoodle',
    'fustylugs', 'fustilarian', 'scullion', 'rampallion', 'gnashgab',
    'gobermouch', 'klazomaniac', 'leasing', 'loiter', 'lubberwort', 'wort',
    'wart', 'muckspout', 'mumblecrust', 'quisby', 'raggabrash', 'rakefire',
    'roiderbanks', 'scobberlotcher', 'skelpie', 'smellfeast', 'sorner',
    'stampcrab', 'stymphalist', 'tallowcatch', 'triptaker', 'wandought',
    'whifflewhaffle', 'yald', 'yaldson', 'zoilist', 'cad', 'cack', 'gorblimey',
    'knob', 'rotter', 'swine', 'tosser', 'tuss', 'spastic', 'sodding', 'worm',
    'donkey', 'llama', 'snake', 'cockroach', 'bull', 'cow', 'harpy', 'troll',
    'goblin', 'gnome', 'elf', 'monster', 'dog', 'stud', 'pig', 'monkey', 'ape',
    'chicken', 'rat', 'hyena', 'good', 'bad', 'evil', 'lame', 'boring', 'fat',
    'lard', 'dirt', 'poo', 'fart', 'suck', 'smelly', 'stinky', 'ugly', 'wild',
    'lazy', 'christ', 'buffoon', 'clown', 'joker', 'dork', 'nerd', 'freak',
    'idiot', 'imbecile', 'dumb', 'nailed', 'slow', 'stupid', 'retard', 'cramp',
    'moron', 'fool', 'smut', 'bottom', 'blows', 'member', 'hang', 'choke',
    'banging', 'lick', 'crack', 'lying', 'slap', 'snot', 'mess', 'sob', 'brag',
    'trash', 'litter', 'dump', 'fist', 'meat', 'hose', 'groin', 'hole',
    'rubber', 'snob', 'stain', 'brat', 'bush', 'alcoholic', 'booze', 'bozo',
    'creep', 'stalker', 'loser', 'sack', 'slime', 'horny', 'gland', 'boogey',
    'rude', 'slave', 'baptême', 'câlisse', 'drunk', 'calvaire', 'ciboire',
    'crisse', 'maudit', 'mauzus', 'osti', 'bugger', 'crikey', 'dingaling',
    'donga', 'flaming', 'muppet', 'stuffed', 'gronk', 'slash', 'root', 'seppo',
    'duff', 'bogan', 'redneck', 'dill', 'onions', 'fugly', 'jonas', 'tassie',
    'mut', 'poofter', 'slagger'
]


cheeses = [
    'Abertam', 'Abondance', 'Ädelost', 'Aghoughlou', 'Aisy', 'Ambrosia', 'Amou',
    'Angelot', 'Annot', 'Aoules', 'Appenzeller', 'Ardrahan', 'Arpitan',
    'Arrigny', 'Arthon', 'Asiago', 'Aura', 'Autun', 'Avalin', 'Bagòss', 'Banon',
    'Barbeillon', 'beaufort', 'Belloc', 'Bergues', 'Bessay', 'Bethmale',
    'Bitto', 'Bleuchâtel', 'Bocconcini', 'Bondard', 'Boucantrin', 'Brézain',
    'Brie', 'Brocciu', 'Brunost', 'Bundz', 'Burrata', 'Butterkäse', 'Cabécou',
    'Cachaille', 'Caerphilly', 'Caillebotte', 'Calinzanincu', 'Camembert',
    'Cantal', 'Carré', 'Castelmagno', 'Cathare', 'Cebreiro', 'Cedenol',
    'Ceshire', 'Chaource', 'Chevrotin', 'Chhurpi', 'Citeaux', 'Claquebitou',
    'Clochette', 'Colombier', 'Comté', 'Coquetdale', 'Cottenham', 'Coulommiers',
    'Crayeux', 'Croglin', 'Danablu', 'Dauphin', 'Délice', 'Derby', 'Dolcelatte',
    'Dovedale', 'Dubliner', 'Dunlop', 'Duprado', 'Durrus', 'Échourgnac', 'Edam',
    'Emmental', 'Époisses', 'Esbareich', 'Etivaz', 'Excelsior', 'Faisselle',
    'Feta', 'Figou', 'Floreffe', 'Fontainebleau', 'Fourme', 'Fricâlin',
    'Gammelost', 'Gaperon', 'Gaztanbera', 'Ġbejna', 'Gien', 'Golka',
    'Gorgonzola', 'Gourmelin', 'Graçay', 'Grevé', 'Gruyère', 'Halloumi',
    'Havarti', 'Huntsman', 'Hushållsost', 'Ibakhbakhane', 'Idiazábal',
    'Irkotta', 'Jarlsberg', 'Jonchée', 'Jura', 'Kasséri', 'Kazemat', 'Kechek',
    'Kefalotýri', 'Kénogami', 'Korbáčik', 'Laguiole', 'Langres', 'Lavort',
    'Lebné', 'Leerdammer', 'Leipäjuusto', 'Lévéjac', 'Liptauer', 'livarot',
    'Llenguat', 'Lormes', 'Maasdam', 'Mâconnais', 'Magor', 'Malakoff',
    'Mamirolle', 'Manchego', 'Maó', 'Maquée', 'Maroilles', 'Mascarpone',
    'Massipou', 'Mató', 'Meilleraye', 'Ménez-Hom', 'Metton', 'Mimolette',
    'Miromando', 'Mizithra', 'Mizotte', 'Montasio', 'Mont-d’Or', 'Morbier',
    'Mothais', 'Mottin', 'Mozzarella', 'Munster', 'Murazzano', 'Murol', 'Năsal',
    'Meufchâtel', 'Niolo', 'Nisa', 'Numidia', 'Obatzda', 'Oelenberg', 'Oka',
    'Mlivet', 'Orval', 'Oscypek', 'Ovalie', 'Palet', 'Panir', 'Parenica',
    'Parmesan', 'Passendale', 'Pavé', 'Pavin', 'Pecorino', 'Pélardon',
    'Penteleu', 'Pérail', 'Persillé', 'Pétafine', 'Picodon', 'Pikauba',
    'Pithiviers', 'Plaisentif', 'Provolone', 'Pultost', 'Pyrénées', 'Rabaçal',
    'Raclette', 'Ragusano', 'Ramequin', 'Raschera', 'Rebarbe', 'Reblochon',
    'Recuite', 'Remoudou', 'Requeijão', 'Ricotta', 'Rigotte', 'Rocamadour',
    'Rochebaron', 'Rocroi', 'Rogallais', 'Rogeret', 'Rollot', 'Roquefort',
    'Rovethym', 'Royalp', 'Saingorlon', 'Salers', 'Santarém', 'Sarasson',
    'Sarteno', 'Savaron', 'Sbrinz', 'Scamorza', 'Sérac', 'Silter', 'Sirene',
    'Soumaintrain', 'Stichelton', 'Stilton', 'Stracchino', 'Șvaițer',
    'Swaledale', 'Takemarit', 'Taleggio', 'Tamié', 'Tarag', 'Taupinette',
    'Telemea', 'Tetilla', 'Thollon', 'Tignard', 'Tilsit', 'Tintern', 'Tomar',
    'Tomme', 'Tracle', 'Trappiste', 'Trecce', 'Tricorne', 'Tuma', 'Tybo',
    'Urdă', 'Vacherin', 'Valbert', 'valençay', 'Venaco', 'Vézelay', 'Vignotte',
    'Villebarou', 'Void', 'Voves', 'Waterloo', 'Yarg'
]


goshdarnits = [
    'airhead', 'all-mighty', 'argle-bargle', 'baboon', 'backdoor', 'backside',
    'badbreath', 'bajeezus', 'balderdash', 'barf-breath', 'beachhouse',
    'beanbag', 'birdbrain', 'blabbermouth', 'bland-bananas', 'blarf', 'blasted',
    'blathering', 'bleedin', 'blimey', 'blockhead', 'bloody', 'blowhard',
    'bocce-balls', 'bogus', 'bollocks', 'bologna', 'bonehead', 'boner', 'boob',
    'booger-breath', 'booger-butt', 'booger-face', 'boogers', 'boogie-face',
    'boom-boom', 'booty', 'braggart', 'brass-pony', 'brat', 'broken-britches',
    'brown-sugar', 'bubble-butt', 'bull-hockey', 'bullspit', 'bully', 'bum',
    'bum-bailey', 'bum-grapes', 'bumbum', 'bumhole', 'bummer', 'bumwad',
    'bunghole', 'bungle-squid', 'bunk-grimbler', 'buns', 'burp', 'butt',
    'butt-brain', 'butt-burglar', 'butt-clown', 'butt-dumpling', 'butt-goblin',
    'butt-horn', 'butt-knocker', 'butt-lover', 'butt-monkey', 'butt-mouth',
    'butt-paste', 'butt-putty', 'butt-sniffer', 'butt-thunder', 'butt-tornado',
    'butt-trumpet', 'butt-ventriloquist', 'butt-wipe', 'buttcheek', 'buttcrack',
    'butthash', 'butthead', 'butthole', 'buttmunch', 'buttock', 'buttscratch',
    'caca', 'cheeky', 'cheese-and-crackers', 'chimp', 'chowderhead',
    'chucklehead', 'chump', 'churlish', 'clod', 'cockroach', 'codger',
    'codpiece', 'codswallop', 'constarn-it', 'cooky', 'coot', 'cornnuts',
    'cotton-head', 'cow-patty', 'coxcomb', 'crackerjack', 'crap',
    'crap-o-mundo', 'crap-slapper', 'crap-twiddling', 'crapola', 'crapple',
    'crappy', 'crassbasket', 'cretin', 'crikey', 'crimeny', 'crinkleberry',
    'cripes', 'crud', 'crum-bum', 'crumby', 'crybaby', 'curses', 'dad-sizzle',
    'dadgum', 'dadgumit', 'dagnabbit', 'dang', 'dangit', 'darn', 'darn-tootin',
    'darn-tootin', 'darnit', 'derriere', 'deuce', 'diarrhea', 'dillhole',
    'dillwad', 'dillweed', 'dimwit', 'ding-dong', 'dingbat', 'dingleberry',
    'dingus', 'dink', 'dipstick', 'dirtbag', 'dirtball', 'dishcloth', 'dodo',
    'dodo-head', 'doggone', 'doggonit', 'doggy-doo', 'doink', 'dolt', 'dong',
    'donger', 'donk', 'donkey', 'donkey-biscuit', 'donut-holes', 'doodie',
    'doodie-nose', 'doodoo', 'doodoo-brains', 'doodoo-head', 'dookie', 'doozie',
    'dope', 'dork', 'doxy', 'drat', 'dullard', 'dumb', 'dumbbell', 'dumbo',
    'dumdum', 'dummy', 'dump', 'dump-fumbler', 'dumplestiltskin', 'dumpling',
    'dunce', 'dust-magnet', 'dweeb', 'eat-my-shorts', 'effin', 'egads',
    'egghead', 'f-bomb', 'fannie', 'farfegnugen', 'farkle', 'fart', 'fart-face',
    'fart-whisperer', 'farthead', 'fartknocker', 'feckless', 'fiddlesticks',
    'fig-newtons', 'flapdoodle', 'flea-bitten', 'flim-flam', 'flip',
    'flippin-flapper', 'flying-saucers', 'fooey', 'fool', 'foolhardy',
    'for-petes-sake', 'fork', 'frack', 'frag', 'freaking', 'frick',
    'frick-frack', 'frickin', 'friggin', 'fudge', 'fudge-nuggets',
    'fudgecicles', 'funky', 'gadsbudlikins', 'gadzooks', 'garsh', 'garsh-darn',
    'gas-blast', 'gee-willikers', 'geek', 'glory-me', 'golly', 'golly-gee',
    'gonad', 'goober', 'goober-brains', 'goober-shavings', 'goober-thief',
    'good-for-nuthin', 'good-grief', 'good-night', 'goodness', 'goofy',
    'googley-moogley', 'goon', 'gorgeous-grandma', 'goshdangit', 'goshdarn',
    'goshdarnit', 'gracious', 'great-scott', 'grime-spangler', 'grin-swisher',
    'grits-and-gravy', 'groin', 'grouch', 'grump-droppings', 'grunt-chortler',
    'gunk-thumping', 'H-E-double-hockey-sticks', 'halfwit', 'hampster',
    'harebrained', 'harpy', 'heavens-to-betsy', 'heck', 'heck-raising',
    'heebee-jeebees', 'hiney', 'hinus', 'hocus-pocus', 'hog', 'hogswallop',
    'hogwash', 'holy-cow', 'holy-crapola', 'holy-frijoles', 'holy-guacamole',
    'holy-moley', 'holy-ship', 'holy-wow', 'hoochie', 'hoochie-coochie',
    'horse-apples', 'horse-feathers', 'horse-pucky', 'hosed', 'hoser',
    'hotheaded', 'hush', 'idiot', 'ignoramus', 'ill-bred', 'imbecile', 'inept',
    'jackanapes', 'jeepers', 'jeez', 'jeez-louise', 'jelly-brained', 'jerk',
    'jiggery-pokery', 'jimminy-crickets', 'jinkies', 'judas-priest',
    'jumpin-jehosephat', 'junk-sling', 'junknuts', 'knave', 'knob',
    'knucklehead', 'leapin-lizards', 'lickspittle', 'lily-livered',
    'loaf-whittler', 'louse', 'lousy', 'lump-sniffer', 'lunkhead', 'malarkey',
    'miser', 'moist-crumpet', 'monday-to-friday', 'moose-berries', 'moron',
    'mother-fathers', 'mother-frigger', 'mother-of-pearl', 'mother-trucker',
    'mothersmucker', 'mouth-breather', 'muck-thumper', 'muckspout', 'mudbutt',
    'mudskipper', 'mule', 'muppet', 'my-word', 'nads', 'nards', 'nerd',
    'nibblits', 'night-soil', 'nimrod', 'nincompoop', 'ninny', 'ninnyhammer',
    'nitwit', 'no-good', 'no-no', 'oaf', 'oddball', 'oof', 'oops', 'oopsie',
    'oopsie-daisy', 'pansy', 'patootie', 'peanut-butter-and-jelly',
    'peas-and-rice', 'peepee', 'peeter', 'piddle', 'pig', 'pinhead', 'plopper',
    'poo', 'poop', 'poop-piler', 'poop-smiler', 'poop-wagon', 'pooper',
    'pooping', 'poopington', 'poopmonster', 'poopoo', 'poopoo-balls',
    'poopoo-face', 'poopoo-head', 'poopsie', 'poopsie-daisy', 'poopy',
    'poopy-mcdoodooface', 'poot', 'poot-scrambler', 'poot-wincer', 'pootie',
    'poppycock', 'potty', 'potty-mouth', 'prat', 'privy', 'puke', 'puny',
    'putz', 'rascal', 'rats', 'razzle-frazzit', 'rear-admiral', 'rootin-tootin',
    'royal-turdship', 'rump', 'sam-hill', 'saucy', 'sazzafraz', 'scat-scraping',
    'schlong', 'schtup', 'scobberlotcher', 'scoundrel', 'screwed', 'scruffy',
    'scuddle-butt', 'scum-tumbler', 'scummy', 'shaft', 'sheesh',
    'shifting-sands', 'shifty', 'ships-and-sailors', 'shmuck', 'shoot',
    'shootdarn', 'shortstack', 'shrew', 'shtick', 'shucks',
    'shut-the-front-door', 'shut-up', 'simpleton', 'skeezy', 'skidmarks',
    'skunk', 'sleasebag', 'sleaseball', 'slimy', 'slob', 'sloth', 'smellfungus',
    'smelly', 'snails', 'snarf', 'snot-nose', 'snot-rocket', 'snotty',
    'sodding', 'son-of-a-biscuit', 'son-of-a-gun', 'splatterhouse', 'squirt',
    'stinker', 'stinky', 'stool', 'stool-pidgeon', 'stupid',
    'sufferin-succotash', 'tallywhacker', 'tarnation', 'tee-tee',
    'teetering-teapots', 'throne-dumpling', 'thunderation', 'ticked-off',
    'tink-sprinkler', 'tinkle', 'tittering-tadpoles', 'todger', 'toe-fungus',
    'tom-foolery', 'tool', 'toot', 'toot-eater', 'toot-scooting', 'toot-wizard',
    'tooter', 'tootle', 'toots', 'trash-panda', 'trump-nugget', 'tuhkus',
    'turd', 'turd-burglar', 'turd-scrambler', 'turd-smuggler', 'turd-whisperer',
    'tushie', 'twig-and-berries', 'twisted-knickers', 'twit', 'ugly', 'upchuck',
    'wafflestomp', 'wang', 'weenie', 'weewee', 'what-the-hay', 'whippersnapper',
    'whoa-nelly', 'whomp-dropper', 'whoops', 'whoopsie', 'wicked', 'wiener',
    'wienus', 'willy', 'wimp-pidgeon', 'wind-breaker', 'yak-smacker',
    'yankeedoodle', 'zoinks', 'zounds',
]


pokes = [
    'Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard',
    'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree',
    'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Rattata',
    'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu',
    'Sandshrew', 'Sandslash', 'Nidoran', 'Nidorina', 'Nidoqueen', 'Nidoran♂',
    'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales',
    'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom',
    'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett',
    'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape',
    'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra',
    'Kadabra', 'Alakazam', 'Machop', 'Machoke', 'Machamp', 'Bellsprout',
    'Weepinbell', 'Victreebel', 'Tentacool', 'Tentacruel', 'Geodude',
    'Graveler', 'Golem', 'Ponyta', 'Rapidash', 'Slowpoke', 'Slowbro',
    'Magnemite', 'Magneton', 'Farfetch\'d', 'Doduo', 'Dodrio', 'Seel',
    'Dewgong', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
    'Gengar', 'Onix', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb',
    'Electrode', 'Exeggcute', 'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee',
    'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon',
    'Chansey', 'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen',
    'Seaking', 'Staryu', 'Starmie', 'Mr.Mime', 'Scyther', 'Jynx', 'Electabuzz',
    'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras', 'Ditto',
    'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar',
    'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos',
    'Moltres', 'Dratini', 'Dragonair', 'Dragonite', 'Mewtwo', 'Mew',
    'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava', 'Typhlosion',
    'Totodile', 'Croconaw', 'Feraligatr', 'Sentret', 'Furret', 'Hoothoot',
    'Noctowl', 'Ledyba', 'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou',
    'Lanturn', 'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
    'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom', 'Marill', 'Azumarill',
    'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom',
    'Sunkern', 'Sunflora', 'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon',
    'Murkrow', 'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
    'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Snubbull',
    'Granbull', 'Qwilfish', 'Scizor', 'Shuckle', 'Heracross', 'Sneasel',
    'Teddiursa', 'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine',
    'Corsola', 'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory',
    'Houndour', 'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2',
    'Stantler', 'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid',
    'Magby', 'Miltank', 'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar',
    'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi', 'Treecko', 'Grovyle',
    'Sceptile', 'Torchic', 'Combusken', 'Blaziken', 'Mudkip', 'Marshtomp',
    'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple',
    'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
    'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull', 'Pelipper',
    'Ralts', 'Kirlia', 'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
    'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
    'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita', 'Hariyama',
    'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron',
    'Lairon', 'Aggron', 'Meditite', 'Medicham', 'Electrike', 'Manectric',
    'Plusle', 'Minun', 'Volbeat', 'Illumise', 'Roselia', 'Gulpin', 'Swalot',
    'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
    'Torkoal', 'Spoink', 'Grumpig', 'Spinda', 'Trapinch', 'Vibrava', 'Flygon',
    'Cacnea', 'Cacturne', 'Swablu', 'Altaria', 'Zangoose', 'Seviper',
    'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt',
    'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo', 'Feebas',
    'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette', 'Duskull',
    'Dusclops', 'Tropius', 'Chimecho', 'Absol', 'Wynaut', 'Snorunt', 'Glalie',
    'Spheal', 'Sealeo', 'Walrein', 'Clamperl', 'Huntail', 'Gorebyss',
    'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon', 'Salamence', 'Beldum', 'Metang',
    'Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios',
    'Kyogre', 'Groudon', 'Rayquaza', 'Jirachi', 'Deoxys', 'Turtwig', 'Grotle',
    'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup', 'Prinplup',
    'Empoleon', 'Starly', 'Staravia', 'Staraptor', 'Bidoof', 'Bibarel',
    'Kricketot', 'Kricketune', 'Shinx', 'Luxio', 'Luxray', 'Budew', 'Roserade',
    'Cranidos', 'Rampardos', 'Shieldon', 'Bastiodon', 'Burmy', 'Wormadam',
    'Mothim', 'Combee', 'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel',
    'Cherubi', 'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon',
    'Drifblim', 'Buneary', 'Lopunny', 'Mismagius', 'Honchkrow', 'Glameow',
    'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor', 'Bronzong',
    'Bonsly', 'MimeJr.', 'Happiny', 'Chatot', 'Spiritomb', 'Gible', 'Gabite',
    'Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Hippopotas', 'Hippowdon',
    'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak', 'Carnivine', 'Finneon',
    'Lumineon', 'Mantyke', 'Snover', 'Abomasnow', 'Weavile', 'Magnezone',
    'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
    'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor', 'Mamoswine',
    'Porygon-Z', 'Gallade', 'Probopass', 'Dusknoir', 'Froslass', 'Rotom',
    'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas',
    'Giratina', 'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin',
    'Arceus', 'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
    'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog', 'Lillipup',
    'Herdier', 'Stoutland', 'Purrloin', 'Liepard', 'Pansage', 'Simisage',
    'Pansear', 'Simisear', 'Panpour', 'Simipour', 'Munna', 'Musharna', 'Pidove',
    'Tranquill', 'Unfezant', 'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore',
    'Gigalith', 'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
    'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad',
    'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede',
    'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil', 'Lilligant',
    'Basculin', 'Sandile', 'Krokorok', 'Krookodile', 'Darumaka', 'Darmanitan',
    'Maractus', 'Dwebble', 'Crustle', 'Scraggy', 'Scrafty', 'Sigilyph',
    'Yamask', 'Cofagrigus', 'Tirtouga', 'Carracosta', 'Archen', 'Archeops',
    'Trubbish', 'Garbodor', 'Zorua‡', 'Zoroark‡', 'Minccino', 'Cinccino',
    'Gothita', 'Gothorita', 'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus',
    'Ducklett', 'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
    'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus', 'Amoonguss',
    'Frillish', 'Jellicent', 'Alomomola', 'Joltik', 'Galvantula', 'Ferroseed',
    'Ferrothorn', 'Klink', 'Klang', 'Klinklang', 'Tynamo', 'Eelektrik',
    'Eelektross', 'Elgyem', 'Beheeyem', 'Litwick', 'Lampent', 'Chandelure',
    'Axew', 'Fraxure', 'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
    'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon', 'Golett',
    'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet', 'Braviary',
    'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino', 'Zweilous',
    'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion', 'Terrakion', 'Virizion',
    'Tornadus', 'Thundurus', 'Reshiram', 'Zekrom', 'Landorus', 'Kyurem',
    'Keldeo', 'Meloetta', 'Genesect', 'Chespin', 'Quilladin', 'Chesnaught',
    'Fennekin', 'Braixen', 'Delphox', 'Froakie', 'Frogadier', 'Greninja',
    'Bunnelby', 'Diggersby', 'Fletchling', 'Fletchinder', 'Talonflame',
    'Scatterbug', 'Spewpa', 'Vivillon', 'Litleo', 'Pyroar', 'Flabébé',
    'Floette', 'Florges', 'Skiddo', 'Gogoat', 'Pancham', 'Pangoro', 'Furfrou',
    'Espurr', 'Meowstic', 'Honedge', 'Doublade', 'Aegislash', 'Spritzee',
    'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
    'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer', 'Helioptile',
    'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura', 'Aurorus', 'Sylveon',
    'Hawlucha', 'Dedenne', 'Carbink', 'Goomy', 'Sliggoo', 'Goodra', 'Klefki',
    'Phantump', 'Trevenant', 'Pumpkaboo', 'Gourgeist', 'Bergmite', 'Avalugg',
    'Noibat', 'Noivern', 'Xerneas', 'Yveltal', 'Zygarde', 'Diancie', 'Hoopa',
    'Volcanion', 'Rowlet', 'Litten', 'Popplio', 'Pikipek', 'Yungoos', 'Grubbin',
    'Rockruff', 'Komala', 'Solgaleo', 'Lunala', 'Magearna'
]

ducks = ['AfricanBlack', 'AfricanPygmyGoose', 'AmericanBlack',
    'AmericanWhiteWingedScoter', 'AmericanWigeon', 'AndeanTeal',
    'AsianWhiteWingedScoter', 'AucklandIslandsTeal', 'AustralasianShoveler',
    'AustralianShel', 'AustralianWood', 'BaersPochard', 'BaikalTeal',
    'BarrowsGoldeneye', 'BlackScoter', 'BlackBelliedWhistling', 'BlackHeaded',
    'Blue', 'BlueBilled', 'BlueWingedGoose', 'BlueWingedTeal',
    'BrazilianMerganser', 'BrazilianTeal', 'BrownTeal', 'Bufflehead',
    'CampbellIslandsTeal', 'Canvasback', 'CapeShoveler', 'CapeTeal',
    'ChestnutTeal', 'ChiloeWigeon', 'CinnamonTeal', 'Comb', 'CommonEider',
    'CommonGoldeneye', 'CommonMerganser', 'CommonPochard', 'CommonScoter',
    'CommonShel', 'CommonTeal', 'CottonPygmyGoose', 'Crested', 'CrestedShel',
    'EasternSpotBilled', 'EatonsPintail', 'EgyptianGoose', 'EurasianWigeon',
    'Falcated', 'FalklandSteamer', 'Ferruginous', 'FlightlessSteamer',
    'FlyingSteamer', 'Freckled', 'FulvousWhistling', 'Gadwall', 'Garganey',
    'GreaterScaup', 'GreenPygmyGoose', 'GreyTeal', 'Hardhead', 'Harlequin',
    'Hartlaubs', 'Hawaiian', 'HoodedMerganser', 'HottentotTeal', 'KelpGoose',
    'KingEider', 'Lake', 'Laysan', 'LesserScaup', 'LesserWhistling',
    'LongTailed', 'Maccoa', 'MadagascarPochard', 'MadagascarTeal', 'Mallard',
    'Mandarin', 'MarbledTeal', 'Masked', 'Mellers', 'Mottled', 'Muscovy',
    'Musk', 'NewZealandScaup', 'NorthernPintail', 'NorthernShoveler',
    'OrinocoGoose', 'PacificBlack', 'ParadiseShel', 'Philippine', 'PinkEared',
    'PinkHeaded', 'PlumedWhistling', 'PunaTeal', 'RadjahShel', 'RedShoveler',
    'RedBilled', 'RedBreastedMerganser', 'RedCrestedPochard', 'Redhead',
    'RingNecked', 'RingedTeal', 'RosyBilledPochard', 'Ruddy', 'RuddyShel',
    'SalvadorisTeal', 'ScalySidedMerganser', 'SilverTeal', 'Smew',
    'SouthAfricanShel', 'SouthernPochard', 'Spectacled', 'SpectacledEider',
    'SpottedMallard', 'SpottedWhistling', 'StellersEider', 'SundaTeal',
    'SurfScoter', 'Torrent', 'Tufted', 'VelvetScoter', 'WanderingWhistling', 'WestIndianWhistling', 'WesternSpotBilled', 'WhiteBacked',
    'WhiteCheekedPintail', 'WhiteFacedWhistling', 'WhiteHeaded',
    'WhiteHeadedSteamer']
